properties:
  adminInterface:
    description: Port or TCP network address (IP address and the port) that the Admin REST API listens on.
    type: string
    default: '127.0.0.1:4985'
  adminUI:
    description: URL of the Sync Gateway Admin Console HTML page.
    type: string
    default: 'localhost:4985/_admin/'
  compressResponses:
    description: Whether to compress HTTP responses. Set to false to disable compression of HTTP responses.
    type: boolean
    default: 'true'
  configServer:
    description: URL of a Couchbase database-configuration server (for dynamic database discovery). A database-configuration server allows Sync Gateway to load a database configuration dynamically from a remote endpoint. If a database configuration server is defined, when Sync Gateway gets a request for a database that it doesn't know about, then Sync Gateway will attempt to retrieve the database configuration properties from the URL ConfigServer/DBname, where DBname is the database name.
    type: string
  CORS:
    description: Configuration object for allowing CORS (cross-origin resource sharing). This is a useful to interact directly with Sync Gateway from HTML 5 applications via XHR.
    type: object
    properties:
      Origin:
        type: array
        items:
          type: string
          description: Comma-separated list of allowed origins; use an asterisk (*) to allow access from everywhere.
      LoginOrigin:
        type: array
        items:
          type: string
          description: Comma-separated list of allowed login origins.
      Headers:
        type: array
        items:
          type: string
          description: Comma-separated list of allowed HTTP headers.
      MaxAge:
        type: integer
        description: Value for the Access-Control-Max-Age header. This is the the number of seconds that the response to a CORS preflight request can be cached before sending another preflight request.
  CouchbaseKeepaliveInterval:
    description: TCP keep-alive interval in seconds between Sync Gateway and Couchbase Server.
    type: integer
  databases:
    description: Database settings.
    type: object
    properties:
      foo_db:
        type: object
        description: The database name is stored as a key.
        properties:
          allow_empty_password:
            type: boolean
            description: Whether to allow empty passwords for Couchbase Server authentication.
            default: 'false'
          bucket:
            type: string
            description: Bucket name on Couchbase Server or a Walrus bucket. The default is the database name.
          cache:
            type: object
            description: Database cache configuration.
            properties:
              max_wait_pending:
                type: integer
                description: Maximum wait time in milliseconds for a pending sequence before skipping sequences.
                default: 5000
              max_num_pending:
                type: integer
                description: Maximum number of pending sequences before skipping the sequence.
                default: 10000
              max_wait_skipped:
                type: integer
                description: Maximum wait time in milliseconds for a skipped sequence before abandoning the sequence.
                default: 3600000
              enable_star_channel:
                type: boolean
                description: Enable the star (*) channel.
                default: 'true'
              channel_cache_max_length:
                type: integer
                description: Maximum number of entries maintained in cache per channel.
                default: 500
              channel_cache_min_length:
                type: integer
                description: Minimum number of entries maintained in cache per channel.
                default: 50
              channel_cache_expiry:
                type: integer
                description: Time (seconds) to keep entries in cache beyond the minimum retained.
                default: 60
          event_handlers:
            type: object
            properties:
              document_changed:
                description: The configuraton for the action to perform when a document change is detected.
                type: array
                items:
                  type: object
                  properties:
                    filter:
                      description: Filter function to determine which documents to post (for a webhook event handler).
                      type: string
                    handler:
                      description: Handler type. The must be webhook.
                      type: string
                    timeout:
                      description: Timeout in seconds (for a webhook event handler).
                      type: integer
                      default: 60
                    url:
                      description: URL to which to post documents (for a webhook event handler).
                      type: string
              max_processes:
                type: integer
                description: Maximum concurrent event handling goroutines. The default is 500.
              wait_for_process:
                type: integer
                description: Maximum wait time in milliseconds when the event queue is full. The default is 5.
          feed_type:
            type: string
            description: Feed type DCP or TAP.
            default: TAP
          offline:
            type: string
            description: Whether the database if kept offline when Sync Gateway starts. Specifying the value true results in the database being kept offline. The default (if the property is omitted) is to bring the database online when Sync Gateway starts. For more information, see Taking databases offline and bringing them online.
          password:
            type: string
            description: Bucket password for authenticating to Couchbase Server. There is no default.
          pool:
            type: string
            description: Couchbase pool name. The default is the string default.
          rev_cache_size:
            type: integer
            description: Size of the revision cache, specified as the total number of document revisions to cache in memory for all recently accessed documents. When the revision cache is full, Sync Gateway removes less recent document revisions to make room for new document revisions. Adjust this property to tune memory consumption by Sync Gateway, for example on servers with less memory and in cases when Sync Gateway creates many new documents and/or updates many documents relative to the number of read operations.
            default: 5000
          revs_limit:
            type: integer
            description: Maximum depth to which a document's revision tree can grow.
            default: 1000
          roles:
            type: object
            description: Admin roles
            properties:
              foo_role:
                type: object
                properties:
                  admin_channels:
                    type: array
                    items:
                      description: Channel name.
                      type: string
          server:
            type: string
            description: Couchbase Server (or Walrus) URL. The default is walrus.
          sync:
            type: string
            description: Sync function, which defines which users can read, update, or delete which documents. The default is a default sync function. For more information, see the section Sync function API.
          username:
            type: string
            description: Bucket username for authenticating to Couchbase Server. There is no default.
          users:
            type: object
            properties:
              foo_user:
                type: object
                properties:
                  password:
                    type: string
                    description: The user's password.
                  admin_channels:
                    type: array
                    items:
                      description: Channel name.
                      type: string
                  admin_roles:
                    type: array
                    items:
                      description: Role name.
                      type: string
                  disabled:
                    type: boolean
                    description: Whether this user account is disabled.
  facebook:
    description: Configuration for Facebook Login authentication.
    type: object
    properties:
      register:
        description: 'Whether the Facebook Login server will register new user accounts (true or false)'
        type: boolean
        default: 'false'
  interface:
    description: Public REST API port.
    type: boolean
    default: ':4984'
  log:
    description: Comma-separated list of log keys to enable for diagnostic logging. Use ["*"] to enable logging for all log keys. See Log keys. The default is HTTP.
    type: array
    items:
      type: string
    default: '["*"]'
  logFilePath:
    description: Absolute or relative path on the filesystem to the log file. A relative path is from the directory that contains the Sync Gateway executable file.
    type: string
    default: 'stderr'
  maxCouchbaseConnections:
    description: Maximum number of sockets to open to a Couchbase Server node.
    type: integer
    default: 16
  maxCouchbaseOverflow:
    description: Maximum number of overflow sockets to open.
    type: integer
  maxFileDescriptors:
    description: Maximum number of open file descriptors.
    type: integer
    default: 5000
  maxHeartbeat:
    description: Maximum heartbeat value for _changes feed requests (in seconds).
    type: integer
  maxIncomingConnections:
    description: Maximum number of incoming HTTP connections to accept.
    type: integer
  pretty:
    description: Whether to pretty-print JSON responses.
    type: boolean
    default: 'false'
  profileInterface:
    description: TCP network address (IP address and the port) that the Go profile API listens on. You can obtain go profiling information from the interface. You can omit the IP address.
    type: string
  serverReadTimeout:
    description: Maximum duration in seconds before timing out the read of an HTTP(S) request.
    type: integer
  serverWriteTimeout:
    description: Maximum duration in seconds before timing out the write of an HTTP(S) response.
    type: integer
  slowServerCallWarningThreshold:
    description: Log warnings if database calls made by Sync Gateway take this many milliseconds or longer.
    type: integer
    default: 200
  SSLCert:
    description: Absolute or relative path on the filesystem to the TLS certificate file, if TLS is used to secure Sync Gateway connections, or "nil" for plaintext. A relative path is from the directory that contains the Sync Gateway executable file.
    type: string
  SSLKey:
    description: Absolute or relative path on the filesystem to the TLS private key file, if TLS is used to secure Sync Gateway connections, or "nil" for plaintext. A relative path is from the directory that contains the Sync Gateway executable file.
    type: string
